In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

In [2]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis = 0)

In [9]:
print(cal)
print(cal.shape)

[ 59.  239.  155.4  76.9]
(4,)


In [6]:
percentage = 100*A/cal.reshape(1,4)

In [10]:
cal_new = cal.reshape(1,4)
print(cal_new)
print(cal_new.shape)

[[ 59.  239.  155.4  76.9]]
(1, 4)


In [11]:
print(A.shape)

(3, 4)


In [7]:
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [12]:
a = np.random.randn(5)

In [13]:
print(a)

[ 0.59206506 -0.18711323 -1.49406774  0.09428778  0.57041568]


In [14]:
print(a.shape)

(5,)


In [15]:
print(a.T)

[ 0.59206506 -0.18711323 -1.49406774  0.09428778  0.57041568]


In [16]:
print(np.dot(a, a.T))

2.9520550530706613


In [17]:
a = np.random.randn(5,1)

print(a)

[[-0.39333532]
 [-0.51237632]
 [ 0.83963225]
 [ 1.03114868]
 [ 0.85042217]]


In [18]:
print(a.T)

[[-0.39333532 -0.51237632  0.83963225  1.03114868  0.85042217]]


In [19]:
print(np.dot(a, a.T))

[[ 0.15471267  0.2015357  -0.33025702 -0.40558719 -0.33450107]
 [ 0.2015357   0.26252949 -0.43020769 -0.52833617 -0.43573619]
 [-0.33025702 -0.43020769  0.70498232  0.86578569  0.71404189]
 [-0.40558719 -0.52833617  0.86578569  1.0632676   0.8769117 ]
 [-0.33450107 -0.43573619  0.71404189  0.8769117   0.72321787]]


In [20]:
a = np.random.randn(3,3)

b = np.random.randn(3,1)

c = a*b

In [21]:
print('a is ')
print(a)

a is 
[[-0.24280093  0.22298634  0.04773466]
 [-1.61998909 -0.06426987 -1.39356757]
 [ 1.15559753 -0.0394225  -0.42239114]]


In [22]:
print('b is ')
print(b)

b is 
[[ 1.09336355]
 [-0.55049732]
 [-0.82534104]]


In [23]:
print('c is ')
print(c)

c is 
[[-0.26546969  0.24380514  0.05219134]
 [ 0.89179965  0.03538039  0.76715521]
 [-0.95376207  0.03253701  0.34861675]]


In [24]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [25]:
image.shape[0]

3

In [26]:
image.shape[1]

3

In [27]:
image.shape[2]

2

In [28]:
image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])